foundersandcoders/our-site

- _content/apply.md
> apply typos

- _content/product-management.md
> Services copy

- _content/react.md
@MIJOTHY could you take a look at this and adapt to taste?
> content for react training

- services/content-management.md
Optional wording to avoid repetition of terms.
> CMS suggestions for variety

- _harp/academy/_apply.md
Was going to raise an issue on this, but thought it would take me exactly the same amount of time to write the issue or just do the work seeing as it's so minor! :+1:
> Strikes through past June 15th academy application deadline

- file-upload-tutorial.md
Hey, here is the blog requested at https://github.com/rub1e/beam-me-up-hapi/issues/10
Let me know any edits, suggestions, improvements, expansions, corrections or alterations you have.
> draft of the blog post

- _harp/academy/_faq.md
Reverts foundersandcoders/oursite#128
> Revert "Update _faq.md"

- _harp/about/blog/fac3.md
- _harp/candidates/_candidates.md
Hey!
Just updating information about me in the fac3 blog, and taking my name out of the candidates page.
Cheers :beer:
> Taking my name out of the candidates list, and updating my "status"

- _harp/academy/_about.md
> Possible typo

- _harp/academy/_faq.md
@sofer - does that look right? It's by far the most common question that comes via the contact form so worth having in the FAQ
> updated FAQ with note about int'l students

- _harp/academy/_faq.md
And removed Question about becoming a fee-paying member, until we have greater clarity about what this actually means. Also tweaked the balance of weeks between foundation and real-world projects
> Stronger "give something back" message in faq

- _harp/academy/_faq.md
added course dates to FAQ - This is the most common question from the contact form
Plus updated the "no fees" bit
> updated FAQs

- _harp/agency/portfolio/stockport.md
added space after markdown hashtags
> visible hashtags

- _harp/academy/_prerequisites.md
Taken from https://github.com/FAC6/FAC7/blob/master/curriculum/prereqs.md
> The new prerequisites

- _harp/agency/index.ejs
- _harp/agency/services/application-development.md
- _harp/agency/services/prototyping.md
- _harp/training/_request.md
Reduction in services links from 6 to 3 and link to dwyl.
> changes to services copy

- _harp/agency/services/prototyping.md
Updated copy for prototyping service.
> Prototype faq

- _harp/_partials/navbar.ejs
- _harp/index.ejs
- _harp/testimonials/index.ejs
AGENCY -> HIRE US
Removed EMPLOYERS  and PARTNERS
Added TESTIMONALS
> new navbar

- _harp/academy/_why.md
> Removed "frontend" para from whyjs blurb

- _harp/_webrtc.md
- _harp/webrtc.ejs
Sorry, pulling this one myself, because I need to get it up.
> webrtc page

- _harp/academy/_faq.md
**Note: don't merge until after our meeting in March**
Changed it so that it is clear that people should not expect to earn before 16 weeks.
> FAQ: change dates and added Q

- _harp/about/_company.md
- _harp/academy/_apply.md
- _harp/academy/_faq.md
- _harp/academy/index.ejs
- _harp/index.ejs
Mainly, a much truncated opening page, pending better copy, a tweaked application page and a re-write of the about section.
> new copy in several places

- _harp/academy/_apply.md
@sofer You were a little quick on the trigger with #220 so I didn't have a chance to add my comments ☺️ 
Instead, I've added some suggestions here and will add comments to explain.
**NOTE: No idea where the merge conflicts are coming from, will sort this out now**
Ah, they came from a commit to master. https://github.com/foundersandcoders/oursite/commit/ad7df56204dca7858b8aee3fbc7fbfc7e2f84170
We may have just made the same changes 😆 Updated now, ready for review.
> Application updates

- _harp/css/layout/_copy.scss
- _harp/founders/_accelerators.md
@rebeccaradding want to give it a go?
> new accelerator copy without sources

- _harp/apply.ejs
> rogue redirect

- _harp/404.ejs
> nav added to 404 page

- _harp/apply/_apply.md
- _harp/apply/index.ejs
- _harp/css/base/_fonts.scss
You should be able to see the changes to the apply page here https://oursite-sofer.c9users.io/apply/.
Please merge and I will re-publish.
> new application guidelines

- _harp/coders/faq/index.ejs
- _harp/coders/index.ejs
Last one of the evening, I think.
> fixed a couple of freshly-broken links

- _harp/apply/_apply.md
- _harp/apply/index.ejs
- _harp/css/main.scss
- _harp/css/pages/_apply.scss
css and markdown for apply page
> Apply copy

- _harp/_partials/navlinks.ejs
- _harp/css/features/_navbar.scss
> add apply to nav bar

- _harp/about/_company.md
- _harp/about/_history.md
- _harp/about/_press.md
-Edited the paragraph with dan's changes on 'history' paragraph, hence closed last pull request and added it to this pull request. 
Issues: #281 #283
> About links 

- _harp/about/_company.md
- _harp/about/_history.md
- _harp/about/_press.md
Added new link for video on Our story page.
Issue: #281
> Video about page

- _harp/_partials/navlinks.ejs
- _harp/community/_team.md
Changes link name from COMMUNITY to OUR TEAM
issue #277
> Change nav bar link and heading to team page.

- _harp/about/_company.md
- _harp/about/_history.md
- _harp/about/_press.md
revert commit made accidentally into master
> Revert "Fix link"

- _harp/about/_press.md
fixed link indentation in press section, our story ipage
issue: #298
> fixed link indentation in press section, our story page

- _harp/programme/_overview.md
We don't want a video on the programme page. fixes #280
> remove video from programme page

- _harp/_partials/partners.ejs
> adding links to partner logos

- _harp/programme/index.ejs
> :bug: fix course-information link on home page

- _harp/css/features/_contact.scss
> grow social media icons for large screens

- _harp/_layout.ejs
> HTML title to include Nazareth

- _harp/css/components/_button.scss
> Fixes #234 button padding

- _harp/programme/_overview.md
Added a link to FAC student agreement on Employment section on
programme page. Ready for review
> Link to FAC student agreement #178

- _harp/breathe-with-me/_content.md
- _harp/breathe-with-me/index.ejs
- _harp/css/components/_button.scss
- _harp/css/main.scss
- _harp/css/pages/_projects.scss
> Case study, issue#318

- _harp/apply/_apply.md
- _harp/programme/_overview.md
> Addition of part-time programme to application page + moving Meetup link to programme page

- _harp/_partials/contact.ejs
- _harp/_partials/footer.ejs
- _harp/_partials/partners.ejs
- _harp/_partials/testimonial.ejs
- _harp/about/blog/fac3.md
- _harp/community/_team.md
- _harp/index.ejs
- _harp/testimonials/full/bes.md
- _harp/testimonials/full/izaak.md
- _harp/testimonials/full/jack.md
- _harp/testimonials/full/natalia.md
- _harp/testimonials/full/nikhila.md
> Remove target=_blank from anchor tags

- _harp/css/pages/landing/_landing-page.scss
> media logos match partners

- _harp/css/pages/landing/_landing-page.scss
- _harp/index.ejs
> testimonial link opacity

- _harp/css/features/_navbar.scss
> fix overflowing links

- _harp/apply/_apply.md
> Update _apply.md to reflect new dates.

- _harp/css/pages/landing/_landing-page.scss
- _harp/index.ejs
* add Nazareth button to landing page
* add London button to landing page
* remove Course info button from landing page
>  related to #394

- _harp/apply/_apply.md
Have made a few changes including:
- Changes to video question as decided on here: https://github.com/foundersandcoders/london-selection/issues/25
- Added key dates related to summer 2017 application / course dates
- A few changes to wording, adding some clarity regarding GitHub pages
Further changes or feedback welcome, we ideally need to do this by tomorrow though!!
> Apply page changes

- _harp/apply/_apply.md
In step 6 of the application process it initially said **Why do you want to do join the programme**. So I have deleted the extra do in front of join. Relates to Issue #408.
> Deleted typo

- _harp/apply/_apply.md
- _harp/programme/_overview.md
+ Added application deadlines to the "Apply" page & presented this so that the dates are more prominent
+ Added cohort dates to the "Programme" page
Fixes #401 
(somehow messed up the last attempt https://github.com/foundersandcoders/our-site/pull/402 :laughing: )
> make application dates clearer

- _harp/CNAME
instead of https://github.com/foundersandcoders/our-site/pull/416
> Flattened the domain in CNAME

- _harp/_harp.json
> competitive

- _harp/apply/_apply.md
OK!
Ready for review
goals: 
1) to make this page as clear as possible
2) to make the registration process as short as possible
> edit apply page

- _harp/about/_press.md
> remove double citation

- _harp/apply/prerequisites/_github.md
Change `codingforeveryone/nazareth-channel` to `codingforeveryone/nazareth`
relates #440
> change gitter c4e from nazareth-channel to nazareth room

- _harp/apply/_london.md
#444 
clarify about completing prereqs and getting an interview.
> clarify text in London apply

- _harp/apply/_nazareth.md
Clarifies interview schedule and course prerequisites for internationals
> Clarify interviews

- _harp/apply/_london.md
> Remove guarantee

- _harp/apply/_nazareth.md
relates https://github.com/foundersandcoders/nazareth-programme/issues/161
> adds extra links to where the classroom of Founders and Coders of Nazareth is located

- _harp/apply/prerequisites/_codewars.md
> specify 5kyu in JavaScript for CodeWars

- _harp/about/_history.md
> add short sentence on FCI in History

- _harp/programme/course-information/_london.md
> update London 2018 dates

- _harp/apply/_apply.md
- _harp/apply/_nazareth.md
- _harp/apply/nazareth.ejs
- _harp/programme/course-information/_nazareth.md
fixes #478, only @sofer should merge this.
> update Nazareth application to EOI

- _harp/apply/_apply.md
- _harp/apply/london.ejs
- _harp/programme/course-information/_london.md
Also update London application windows for future applicants
fixes #482
> Close London spring 2018 application window

- _harp/index.ejs
Spotted @NataliaLKB 's job description was a little out of date so I took the liberty of checking each of these with what Linkedin says and made the updates
> Updating Job Titles!

- _harp/community/_team.md
> Remove board of trustees from FAC CIC

- _harp/_partials/contact.ejs
> Change of address

- _harp/apply/_apply.md
- _harp/apply/index.ejs
- _harp/apply/prerequisites/_prereq.md
update language around Codewars on prereqs
update London upcoming course dates
Fixes #495, #498
> update apply page with London EOI

- _harp/apply/prerequisites/_prereq.md
> update FCC prereq

- _harp/apply/index.ejs
- _harp/programme/course-information/_london.md
> open FAC15 application

- _harp/apply/_apply.md
> remove London EOI during application window

- _harp/_layout.ejs
Needed to validate our new G Suite account.
> add G Suite verification

- _harp/apply/_apply.md
With extended prerequisites time.
> update language for Winter 2018

- _harp/apply/_apply.md
- _harp/apply/index.ejs
> remove FAC15 application

- _harp/apply/prerequisites/_prereq.md
Add links to random tests and Codewars Gitter room
> be more explicit with kata writing requirements
